name: appp
description: A new Flutter project.



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'







dependencies:
  flutter_swiper_null_safety: ^1.0.2
  bottomreveal: ^2.0.0
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  fonts:
    - family: openSans
      fonts:
        - asset: assets/fonts/openSans.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

  uses-material-design: true    
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
